config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get '/:hash', to: 'welcome#redirect_url', as: :redirect_url
  resources :reduced_urls, only: [:create, :destroy] do
    put 'expire'
    put 'extend_duration'
    get 'stats', to: 'reduced_urls#stats', as: :stats
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click_counter.rb
class ClickCounter < ApplicationRecord
  belongs_to :reduced_url

  def self.click_per_minutes(reduced_url)
    clicks = where(reduced_url: reduced_url)
    labels = reduced_url.build_labels
    values = []
    labels.each do |label|
      values << clicks.select { |c| c[:created_at].between?(label, label.end_of_minute) }.size || 0
    end
    values
  end
end

app/models/reduced_url.rb
class ReducedUrl < ApplicationRecord
  include Rails.application.routes.url_helpers
  validates :original_url, :reduce_hash, :expiration_time, presence: true
  validates :reduce_hash, uniqueness: true
  validate :expiration_time_thirty_minutes, on: :create

  belongs_to :user, optional: true
  belongs_to :unconnected_user, optional: true
  has_many :click_counters, dependent: :destroy

  def is_expired?
    Time.now > expiration_time
  end

  def build_labels
    labels = []
    time = created_at.beginning_of_minute
    while time < expiration_time.end_of_minute do
      labels << time
      time += 1.minutes
    end
    labels
  end

  private

  # Validate than interval between creation time and expiration time is of 30 minutes
  # when they are user relation and of 3 minutes without user
  def expiration_time_thirty_minutes
    if expiration_time.present?
      minutes = (expiration_time - Time.now) / 1.minutes
      if user.present?
        errors.add(:expiration_time, "Intervall should be smaller than 30 minutes") if minutes > 30
      else
        errors.add(:expiration_time, "Intervall should be smaller than 3 minutes") if minutes > 3
      end
    end
  end
end

app/models/unconnected_user.rb
class UnconnectedUser < ApplicationRecord
  validates :token, presence: true
  has_many :reduced_urls
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :reduced_urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/user_managements_concern.rb
module UserManagementsConcern
  include ActiveSupport::Concern

  # If user is signed_in return the current_user
  # if user is not signed_in but cookies present return the UnconnectedUser
  # Else create an UnconnectedUser and return the created UnconnectedUser
  def get_user_or_unconnected_user
    if user_signed_in?
      current_user
    else
      if cookies[:unconnected_users].present?
        @unconnected_users = UnconnectedUser.find_by(token: cookies[:unconnected_users])
      else
        token = SecureRandom.hex
        cookies[:unconnected_users] = token
        UnconnectedUser.create(token: token)
      end
    end
  end
end

app/controllers/reduced_urls_controller.rb
class ReducedUrlsController < ApplicationController
  include UserManagementsConcern
  before_action :set_reduced_url, only: :destroy
  before_action :authenticate_user!, only: [:expire, :extend_duration, :destroy]

  def stats
    set_reduced_url
    @labels = @reduced_url.build_labels.map { |label| label.strftime('%Hh%M') }
    @values = ClickCounter.click_per_minutes(@reduced_url)
  end

  # Put /reduced_urls/:reduced_url_id/expire.json
  # Permit to expire the url. it will put the date to current date
  # Is only accessible to connected user
  def expire
    set_reduced_url
    if @reduced_url.update(expiration_time: Time.now)
      render json: @reduced_url
    else
      render json: @reduced_url.errors, status: :unprocessable_entity
    end
  end

  # Put /reduced_urls/:reduced_url_id/extend_duration.json
  # Permit to extend the duration of the url by adding your time to CurrentTime
  # Is only accessible to connected user
  def extend_duration
    set_reduced_url
    if @reduced_url.update(expiration_time: Time.now + params[:expiration_delay].to_i.minutes)
      render json: @reduced_url
    else
      render json: @reduced_url.errors, status: :unprocessable_entity
    end
  end

  # POST /reduced_urls
  # POST /reduced_urls.json
  # Create reduced_url.
  def create
    url = params[:original_url]
    if url.present?
      @url_reducer = UrlReducer.new(url)
      @url_reducer.reduce
      build_reduced_url
      if @reduced_url.save
        params = create_response_params
        render json: params
      else
        render json: @reduced_url.errors, status: :unprocessable_entity
      end
    else
      render json: { errors: 'You should should put an url'}, status: 422
    end
  end

  # DELETE /reduced_urls/1
  # DELETE /reduced_urls/1.json
  def destroy
    @reduced_url.destroy
    respond_to do |format|
      format.html { redirect_to reduced_urls_url, notice: 'Reduced url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Params wich is respond by the create method
  # If user is signed_in it have more params
  def create_response_params
    params = {
        generated_url: @url_reducer.reduce_url,
        reduced_url: @reduced_url,
        stat_path: reduced_url_stats_path(@reduced_url),
      }
    if user_signed_in?
      params[:expire_path] = reduced_url_expire_path(@reduced_url)
      params[:extend_path] = reduced_url_extend_duration_path(@reduced_url)
      params[:delete_path] = reduced_url_path(@reduced_url)
    end
    params
  end

  # Build the new ReducedUrl Instance
  def build_reduced_url
    @reduced_url =  get_user_or_unconnected_user
                    .reduced_urls
                    .build(reduce_url_attributes)
  end

  # Build the expiration_time, if user is not connected it's 3min, if he is
  # Connected it's function of his choice
  def build_expiration_time
    if user_signed_in?
      Time.now + params[:expiration_delay].to_i.minutes
    else
      Time.now + 3.minutes
    end
  end

  # Attributes to build reduced_url
  def reduce_url_attributes
    {
      original_url: @url_reducer.original_url,
      reduce_hash: @url_reducer.reduce_hash,
      expiration_time: build_expiration_time
    }
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_reduced_url
      @reduced_url = get_user_or_unconnected_user.reduced_urls.find(params[:id] || params[:reduced_url_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reduced_url_params
      params.fetch(:reduced_url, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include UserManagementsConcern

  # get /
  # List your reduced_url (connected and unconnected user)
  def index
    @reduced_urls = get_user_or_unconnected_user.reduced_urls.includes(:click_counters).reverse
  end

  # Get /:hash
  # Redirect you to the original url. If it's not expired
  def redirect_url
    reduced_url = ReducedUrl.find_by(reduce_hash: params['hash'])
    if reduced_url.present? && !reduced_url.is_expired?
      reduced_url.click_counters.create
      redirect_to reduced_url.original_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reduced_urls_helper.rb
module ReducedUrlsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.haml
#navbar
  %h1 URL Shortener
  .left-link
    - if user_signed_in?
      = link_to('Sign out', destroy_user_session_path, method: :delete)
    - else
      = link_to('Connection', new_user_session_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HfaUrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,width=device-width,height=device-height,target-densitydpi=device-dpi,user-scalable=yes" />


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reduced_urls/_chart.haml
#chart-part
  %canvas#click-stat-chart

app/views/reduced_urls/_form.html.erb
<%= form_with(model: reduced_url, local: true) do |form| %>
  <% if reduced_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reduced_url.errors.count, "error") %> prohibited this reduced_url from being saved:</h2>

      <ul>
      <% reduced_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reduced_urls/_list.haml
#list
  %table
    %tr.header
      %th Original Url
      %th Shorten URL
      %th N
      %th Creation
      %th Expiration
      %th Actions
    - if reduced_urls.present?
      - reduced_urls.each do |reduce_url|
        %tr
          %td= reduce_url.original_url.truncate(80)
          %td= redirect_url_url(reduce_url.reduce_hash)
          %td= reduce_url.click_counters.size
          %td= l(reduce_url.created_at, format: :short)
          %td.expiration-time= l(reduce_url.expiration_time, format: :short)
          %td
            = link_to('Stats', 'javascript:;', data: { stat_url: reduced_url_stats_path(reduce_url) }, class: 'stat-link')
            - if user_signed_in?
              %span
                = link_to('Expire', 'javascript:;', data: { url: reduced_url_expire_path(reduce_url)}, class: 'update-time-link')
                = link_to('Extend', 'javascript:;', class: 'extend-duration-link')
                = link_to('Delete', 'javascript:;', data: { delete_url: reduced_url_path(reduce_url)}, class: 'delete-link')
          - if user_signed_in?
            %td.expiration-selector.hidden
              Extend
              %input{ id: "expiration_delay_#{reduce_url.id}",
                      class: 'reduce-urls-expiration',
                      type: :range,
                      min: 1,
                      max: 30,
                      value: 30,
                      list: :tickmarks,
                      oninput: "day_delay_#{reduce_url.id}.value=expiration_delay_#{reduce_url.id}.value",
                      data: { url: reduced_url_extend_duration_path(reduce_url) }}
              %output{ id: "day_delay_#{reduce_url.id}", for: :expiration_date }30

app/views/reduced_urls/edit.html.erb
<h1>Editing Reduced Url</h1>

<%= render 'form', reduced_url: @reduced_url %>

<%= link_to 'Show', @reduced_url %> |
<%= link_to 'Back', reduced_urls_path %>

app/views/reduced_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reduced Urls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reduced_urls.each do |reduced_url| %>
      <tr>
        <td><%= link_to 'Show', reduced_url %></td>
        <td><%= link_to 'Edit', edit_reduced_url_path(reduced_url) %></td>
        <td><%= link_to 'Destroy', reduced_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reduced Url', new_reduced_url_path %>

app/views/reduced_urls/new.html.erb
<h1>New Reduced Url</h1>

<%= render 'form', reduced_url: @reduced_url %>

<%= link_to 'Back', reduced_urls_path %>

app/views/reduced_urls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reduced_url_path(@reduced_url) %> |
<%= link_to 'Back', reduced_urls_path %>

app/views/welcome/index.haml
#welcome-index
  .center-container
    #shorter-form
      = text_field_tag(:url, nil, placeholder: 'Paste your URL here', id: 'original_url')
      = submit_tag('Shorten', id: 'submit_original_url', class: 'success')
      - if user_signed_in?
        .custom-interval
          %label Duration (in day)
          %input{ id: :expiration_delay, type: :range, min: 1, max: 30, value: 30, list: :tickmarks, oninput: "day_delay.value=expiration_delay.value"}
          %output{ id: :day_delay, for: :expiration_date }30
      %em.error
      .result.hidden
        %span#shorten-url
        %button#copy-url.success Copy

  = render 'reduced_urls/chart'
  = render 'reduced_urls/list', reduced_urls: @reduced_urls

app/views/welcome/redirect_url.haml
%p Your URL is unvalid. It's possible because of two reasons :
%ul
  %li Your Url doesn't exist
  %li Your Url is expired